import os
import datetime

def save_document(response_text:str, directory:str='./output'):
    """ 
    Export travel plan to Markdown file with proper formatting.
    """

    os.makedirs(directory,exist_ok=True)

    #create markdown content with metadata header
    markdown_content=f"""# Travel Plan

    #**Generated on:** {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
    #**created by:** AI Trip Planner

    ---

    {response_text}

    --- 

    *This document was generated by AI. Please Verify all the information, especially prices and operating hours.*
    """

    try:
        # write to markdown file with utf-8 encoding
        # Generate a unique filename based on timestamp

        timestamp= datetime.datetime.now().strftime('%Y%m%d_%H%M%S')
        filename=f"{directory}/AI_Travel_Plan_{timestamp}.md"

        print(filename)

        with open(filename,'w', encoding='utf-8') as file:
            file.write(markdown_content)

    except Exception as e:
        print(f"Error saving document: {e}")
        return None